-- =====================================================================
-- Ticketa - Schema PostgreSQL local (port din Supabase)
-- Ruleaza in pgAdmin Query Tool conectat la DB "ticketa"
-- =====================================================================

-- Curatare daca rulezi a doua oara
DROP TABLE IF EXISTS public."Cos_Bilet" CASCADE;
DROP TABLE IF EXISTS public."Cos" CASCADE;
DROP TABLE IF EXISTS public."Bilet" CASCADE;
DROP TABLE IF EXISTS public."Evenimente" CASCADE;
DROP TABLE IF EXISTS public."Orase" CASCADE;
DROP TABLE IF EXISTS public."Users" CASCADE;

-- =====================================================================
-- Users
-- =====================================================================
CREATE TABLE public."Users" (
    id_user        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname          text NOT NULL,
    lname          text,
    email          text,
    password       text,
    phone_number   text,
    bday           date,
    role           text,
    company        text,
    creation_date  timestamp with time zone DEFAULT NOW()
);

-- =====================================================================
-- Orase
-- =====================================================================
CREATE TABLE public."Orase" (
    id_oras  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nume     text NOT NULL
);

-- =====================================================================
-- Evenimente
-- =====================================================================
CREATE TABLE public."Evenimente" (
    id_event     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text NOT NULL,
    description  text,
    location     text,
    date         timestamp with time zone,
    organiser    text,
    imgpath      text,
    city         text,
    type         text,                 -- 'fizic' sau 'virtual'
    stoc_bilete  numeric,
    id_user      bigint                -- referinta soft catre Users
);
COMMENT ON TABLE public."Evenimente" IS 'Lista Evenimente';

-- =====================================================================
-- Bilet
-- =====================================================================
CREATE TABLE public."Bilet" (
    id_bilet       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    denumire       text NOT NULL,
    pret           double precision,
    loc_eveniment  text,
    description    text,
    id_event       bigint NOT NULL     -- referinta soft catre Evenimente
);

-- =====================================================================
-- Cos (cos cumparaturi / comanda)
-- =====================================================================
CREATE TABLE public."Cos" (
    id_cos      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "isBought"  boolean NOT NULL DEFAULT false,
    cantitate   bigint,
    pret        double precision,
    created_at  timestamp with time zone DEFAULT NOW(),
    id_user     bigint                 -- referinta soft catre Users
);

-- =====================================================================
-- Cos_Bilet (asociere many-to-many intre Cos si Bilet)
-- =====================================================================
CREATE TABLE public."Cos_Bilet" (
    id_cos_bilet  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cos        bigint NOT NULL,
    id_bilet      bigint,
    cantitate     bigint,
    pret          double precision,
    pret_total    double precision
);

-- =====================================================================
-- Indexuri utile pentru query-uri din aplicatie
-- =====================================================================
CREATE INDEX IF NOT EXISTS idx_evenimente_date    ON public."Evenimente" (date);
CREATE INDEX IF NOT EXISTS idx_evenimente_type    ON public."Evenimente" (type);
CREATE INDEX IF NOT EXISTS idx_evenimente_iduser  ON public."Evenimente" (id_user);
CREATE INDEX IF NOT EXISTS idx_bilet_idevent      ON public."Bilet" (id_event);
CREATE INDEX IF NOT EXISTS idx_cos_iduser         ON public."Cos" (id_user);
CREATE INDEX IF NOT EXISTS idx_cos_isBought       ON public."Cos" ("isBought");
CREATE INDEX IF NOT EXISTS idx_cosbilet_idcos     ON public."Cos_Bilet" (id_cos);
CREATE INDEX IF NOT EXISTS idx_users_email        ON public."Users" (email);

-- Verificare rapida
SELECT 'Schema creata cu succes' AS status;
